SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(TS.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A, BOOK B,
     (SELECT B.BOOK_ID, (B.PRICE * SUM(S.SALES)) AS TOTAL_SALES
      FROM BOOK B, BOOK_SALES S
      WHERE TO_CHAR(S.SALES_DATE, 'YYYYMM') = 202201
            AND B.BOOK_ID = S.BOOK_ID
      GROUP BY B.BOOK_ID, B.PRICE
     ) TS
WHERE 1 = 1
      AND A.AUTHOR_ID = B.AUTHOR_ID
      AND B.BOOK_ID = TS.BOOK_ID
GROUP BY A.AUTHOR_NAME, A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;