SELECT  TO_NUMBER(TO_CHAR(START_DATE,'MM')) AS MONTH
        ,CAR_ID
        ,COUNT(HISTORY_ID) AS RECORDS
FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY MM
WHERE   EXISTS (
            SELECT  1
            FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE   START_DATE BETWEEN TO_DATE('20220801','YYYY-MM-DD') 
                                AND TO_DATE('20221031','YYYY-MM-DD')
            AND     CAR_ID = MM.CAR_ID
            GROUP BY CAR_ID
            HAVING COUNT(HISTORY_ID) >= 5
        )
AND START_DATE BETWEEN TO_DATE('20220801','YYYY-MM-DD') 
               AND TO_DATE('20221101','YYYY-MM-DD')
GROUP BY TO_CHAR(START_DATE,'MM'), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC
;