SELECT DISTINCT A.CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
    , CAR_RENTAL_COMPANY_CAR b
WHERE to_char(a.START_DATE, 'YYYYMM') = '202210' 
AND A.CAR_ID = B.CAR_ID
AND b.CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC
;