SELECT '/home/grep/src/' || A.BOARD_ID || '/' 
        || FILE_ID || FILE_NAME|| FILE_EXT AS FILE_PATH
FROM USED_GOODS_BOARD a, USED_GOODS_FILE b
WHERE a.BOARD_ID = b.BOARD_ID
AND a.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY b.FILE_ID DESC
;